// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuzdqoooizqmecvllgbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1emRxb29vaXpxbWVjdmxsZ2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTk4NTAsImV4cCI6MjA2NjEzNTg1MH0.sNs6uGFzOs-OTFBlqjsb1iy1JZapsSgY_HMVbuXKCNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);